#!/bin/bash
set -euo pipefail

export PROJECT_ROOT="/media/ham/EXT4/PROJETO_LIGEM_HIBRIDO"
export HOST_ROOT="$PROJECT_ROOT"
export P2_CODE_ROOT="$PROJECT_ROOT/03_Scripts_Common/P2/L40S"
export P2_CODE_DIR="$P2_CODE_ROOT/V0.1"

# Raiz unica do projeto. Todos os dados, modelos, tiles, resultados e scripts
# operacionais devem estar abaixo de PROJECT_ROOT.
export PIPELINE_NAME="${PIPELINE_NAME:-P2_Hibrido_Post_IA}"
export P2_PIPELINE_KIND="${P2_PIPELINE_KIND:-infer}"

# Versionamento P2. Edite estes valores aqui, nao no comando de execucao.
export P2_TRAIN_VERSION="V0.1"
export P2_INFER_VERSION="V0.1"
export P2_MODEL_VERSION="V0.1"

export DATASET="${DATASET:-Dataset_03}"
export GPU="${GPU:-5060Ti}"
export P2_EXECUTION_MODE="${P2_EXECUTION_MODE:-live}"

case "$P2_PIPELINE_KIND" in
    train)
        export P2_PIPELINE_VERSION="$P2_TRAIN_VERSION"
        ;;
    infer)
        export P2_PIPELINE_VERSION="$P2_INFER_VERSION"
        ;;
    *)
        printf 'ERRO: P2_PIPELINE_KIND nao suportado: %s\n' "$P2_PIPELINE_KIND" >&2
        printf 'Valores suportados: train, infer\n' >&2
        exit 1
        ;;
esac

case "$GPU" in
    5060Ti|RTX5060Ti)
        export GPU="RTX5060Ti"
        export GPU_PROFILE="blackwell_local"
        export GROUND_BATCH_SIZE_DEFAULT="2"
        ;;
    L40S)
        export GPU="L40S"
        export GPU_PROFILE="ada_lab"
        export GROUND_BATCH_SIZE_DEFAULT="8"
        ;;
    B300)
        export GPU="B300"
        export GPU_PROFILE="production_cluster"
        export GROUND_BATCH_SIZE_DEFAULT="16"
        ;;
    *)
        printf 'ERRO: GPU nao suportada: %s\n' "$GPU" >&2
        printf 'Valores suportados: RTX5060Ti, L40S, B300\n' >&2
        exit 1
        ;;
esac

export PYTHON_BIN="${PYTHON_BIN:-python3}"
export TAO_DOCKER_COMPOSE_FILE="$P2_CODE_DIR/docker-compose.tao.yaml"
export DATA_HOST_BASE="$PROJECT_ROOT/02_Pipelines_LIGEM/$PIPELINE_NAME"
export DATA_HOST="$DATA_HOST_BASE/$P2_PIPELINE_KIND/$P2_PIPELINE_VERSION"
export TAO_DATA_HOST="$DATA_HOST_BASE"
export SCRIPTS_HOST="$P2_CODE_ROOT"
export RESULTS_HOST="$DATA_HOST/results"
export TAO_IMAGE="${TAO_IMAGE:-nvcr.io/nvidia/tao/tao-toolkit:6.26.3-pyt}"
export P2_ENV="${P2_ENV:-$GPU}"
export TAO_CONTAINER_DATA_ROOT="${TAO_CONTAINER_DATA_ROOT:-/data}"
export TAO_CONTAINER_SCRIPTS_ROOT="${TAO_CONTAINER_SCRIPTS_ROOT:-/scripts}"
export TAO_CONTAINER_RESULTS_ROOT="${TAO_CONTAINER_RESULTS_ROOT:-/results}"

case "$DATASET" in
    Dataset_01) export DATASET_SLUG="DS1" ;;
    Dataset_02) export DATASET_SLUG="DS2" ;;
    Dataset_03) export DATASET_SLUG="DS3" ;;
    Dataset_04) export DATASET_SLUG="DS4" ;;
    *) export DATASET_SLUG="$DATASET" ;;
esac

export WORKSPACE="$DATA_HOST/workspace_${DATASET_SLUG}/${GPU}"
export LOG_DIR="$DATA_HOST/logs"
export PIPELINE_LOG="$LOG_DIR/pipeline_p2_${P2_PIPELINE_KIND}_${P2_PIPELINE_VERSION}_${DATASET}.log"
export METRICS_CSV="$LOG_DIR/performance_p2_metrics_${P2_PIPELINE_KIND}_${P2_PIPELINE_VERSION}_${DATASET}.csv"

export OUTPUT_DATASET_DIR="$HOST_ROOT/04_Produtos_Finais/$PIPELINE_NAME/$P2_PIPELINE_KIND/$P2_PIPELINE_VERSION/$DATASET_SLUG"
export OUTPUT_PATH="$OUTPUT_DATASET_DIR/${GPU}"

export RAW_DIR="$WORKSPACE/raw"
export NORMALIZED_DIR="$WORKSPACE/normalized"
export TILES_DIR="$WORKSPACE/tiles"
export CLASSIFIED_DIR="$WORKSPACE/classified"
export RASTERS_DIR="$WORKSPACE/rasters"
export VECTORS_DIR="$WORKSPACE/vectors"
export REPORTS_DIR="$WORKSPACE/reports"
export MANIFESTS_DIR="$REPORTS_DIR/manifests"

export ORIGINAL_IMAGES_DIR="$PROJECT_ROOT/00_Datasets/$DATASET/raw_images"
export P2_INPUT_POINT_CLOUD="$PROJECT_ROOT/06_External_Processing/DS03/ODM_Densa_DS3.laz"
export P2_NORMALIZE_MODE="${P2_NORMALIZE_MODE:-passthrough}"
export NORMALIZED_POINT_CLOUD="$NORMALIZED_DIR/dense_cloud_normalized.${P2_INPUT_POINT_CLOUD##*.}"

export INGEST_MANIFEST_JSON="$MANIFESTS_DIR/m01_ingest.json"
export DIAGNOSTIC_JSON="$REPORTS_DIR/diagnostic_${DATASET_SLUG}.json"
export PREPROCESS_MANIFEST_JSON="$MANIFESTS_DIR/m03_preprocess.json"
export GROUND_AI_MANIFEST_JSON="$MANIFESTS_DIR/m04_ground_ai.json"
export DTM_MANIFEST_JSON="$MANIFESTS_DIR/m05_dtm.json"
export REFINE_MANIFEST_JSON="$MANIFESTS_DIR/m06_refine_dtm.json"
export CONTOUR_MANIFEST_JSON="$MANIFESTS_DIR/m07_contours.json"
export QUALITY_REPORT_JSON="$REPORTS_DIR/quality_${DATASET_SLUG}.json"
export GROUND_MODEL_NAME="segformer"
export MODEL_REGISTRY_ROOT="$DATA_HOST_BASE/models/$GROUND_MODEL_NAME/$P2_MODEL_VERSION"
if [[ "$P2_PIPELINE_KIND" == "train" ]]; then
    export GROUND_TAO_RESULTS_DIR="$MODEL_REGISTRY_ROOT/tao_runs"
else
    export GROUND_TAO_RESULTS_DIR="$RESULTS_HOST/${DATASET_SLUG}/${GPU}/tao_runs/segformer"
fi
export GROUND_TAO_DEFAULT_SPECS_DIR="$RESULTS_HOST/${DATASET_SLUG}/${GPU}/tao_specs/defaults/segformer"
export GROUND_TAO_SPEC_FILE="$P2_CODE_DIR/tao_specs/segformer_experiment_ds3.yaml"
export GROUND_DATASET_ROOT="$TILES_DIR/segformer_ds3"
export GROUND_DATASET_MANIFEST="$GROUND_DATASET_ROOT/metadata/dataset_manifest.json"
export GROUND_CLASSES_MANIFEST="$GROUND_DATASET_ROOT/metadata/classes.json"
export GROUND_GENERATED_SPEC_FILE="$GROUND_TAO_RESULTS_DIR/experiment_train_generated.yaml"

export CLASSIFIED_POINT_CLOUD="$CLASSIFIED_DIR/dense_cloud_ground_ready.${P2_INPUT_POINT_CLOUD##*.}"
export DTM_RAW_TIF="$RASTERS_DIR/DTM_raw_${DATASET_SLUG}.tif"
export DTM_REFINED_TIF="$RASTERS_DIR/DTM_refined_${DATASET_SLUG}.tif"
export DSM_TIF="$RASTERS_DIR/DSM_${DATASET_SLUG}.tif"
export VOID_MASK_TIF="$RASTERS_DIR/void_mask_${DATASET_SLUG}.tif"
export CONFIDENCE_TIF="$RASTERS_DIR/confidence_${DATASET_SLUG}.tif"

export P2_01_ENABLED="${P2_01_ENABLED:-1}"
export P2_02_ENABLED="${P2_02_ENABLED:-1}"
export P2_03_ENABLED="${P2_03_ENABLED:-1}"
export P2_04_ENABLED="${P2_04_ENABLED:-0}"
export P2_05_ENABLED="${P2_05_ENABLED:-0}"
export P2_06_ENABLED="${P2_06_ENABLED:-0}"
export P2_07_ENABLED="${P2_07_ENABLED:-0}"
export P2_08_ENABLED="${P2_08_ENABLED:-0}"

export TILE_SIZE_METERS="${TILE_SIZE_METERS:-128}"
export TILE_OVERLAP_METERS="${TILE_OVERLAP_METERS:-32}"
export PREPROCESS_VOXEL_SIZE_METERS="${PREPROCESS_VOXEL_SIZE_METERS:-0.10}"
export PREPROCESS_MIN_TILE_AREA_PERCENT="${PREPROCESS_MIN_TILE_AREA_PERCENT:-25}"
export PREPROCESS_LABEL_SOURCE="${PREPROCESS_LABEL_SOURCE:-auto}"
export PREPROCESS_ASPRS_GROUND_CLASSES="${PREPROCESS_ASPRS_GROUND_CLASSES:-2}"
export PREPROCESS_ASPRS_VEGETATION_CLASSES="${PREPROCESS_ASPRS_VEGETATION_CLASSES:-3,4,5}"
export PREPROCESS_ASPRS_BUILDING_CLASSES="${PREPROCESS_ASPRS_BUILDING_CLASSES:-6}"
export PREPROCESS_ASPRS_PAVED_SURFACE_CLASSES="${PREPROCESS_ASPRS_PAVED_SURFACE_CLASSES:-11}"
export PREPROCESS_ASPRS_WATER_CLASSES="${PREPROCESS_ASPRS_WATER_CLASSES:-9}"
export PREPROCESS_MIN_LABELED_POINT_PERCENT="${PREPROCESS_MIN_LABELED_POINT_PERCENT:-5}"

export GROUND_BATCH_SIZE="${GROUND_BATCH_SIZE:-$GROUND_BATCH_SIZE_DEFAULT}"
export GROUND_DEVICE="${GROUND_DEVICE:-cuda:0}"
export GROUND_TAO_SUBCOMMAND="${GROUND_TAO_SUBCOMMAND:-train}"
export GROUND_TAO_EXTRA_ARGS="${GROUND_TAO_EXTRA_ARGS:-}"
export GROUND_TRAIN_EPOCHS="${GROUND_TRAIN_EPOCHS:-1}"
export GROUND_TRAIN_WORKERS="${GROUND_TRAIN_WORKERS:-2}"

export DTM_RESOLUTION="${DTM_RESOLUTION:-0.20}"
export DTM_INTERPOLATION="${DTM_INTERPOLATION:-idw}"
export DTM_POWER="${DTM_POWER:-2.0}"
export DTM_SEARCH_RADIUS="${DTM_SEARCH_RADIUS:-1.5}"

export REFINE_FILL_DISTANCE="${REFINE_FILL_DISTANCE:-20}"
export REFINE_SMOOTHING_PASSES="${REFINE_SMOOTHING_PASSES:-1}"
export REFINE_PRESERVE_BREAKLINES="${REFINE_PRESERVE_BREAKLINES:-1}"

export CONTOUR_INPUT_MODE="${CONTOUR_INPUT_MODE:-DTM_REFINED}"
export CONTOUR_INTERVAL="${CONTOUR_INTERVAL:-1.0}"
export CONTOUR_BASE="${CONTOUR_BASE:-0.0}"
export CONTOUR_FIELD_NAME="${CONTOUR_FIELD_NAME:-elev}"
export CONTOUR_FORMAT="${CONTOUR_FORMAT:-GPKG}"
export CONTOUR_LAYER_NAME="${CONTOUR_LAYER_NAME:-contours_1m}"
export CONTOUR_OUTPUT="$VECTORS_DIR/contours_1m_${DATASET_SLUG}.gpkg"
export CONTOUR_BAND="${CONTOUR_BAND:-1}"
export CONTOUR_IGNORE_NODATA="${CONTOUR_IGNORE_NODATA:-1}"
export CONTOUR_3D="${CONTOUR_3D:-0}"

p2_ensure_dirs() {
    mkdir -p "$DATA_HOST" "$TAO_DATA_HOST" "$SCRIPTS_HOST" "$RESULTS_HOST"
    mkdir -p "$WORKSPACE" "$LOG_DIR" "$OUTPUT_DATASET_DIR" "$OUTPUT_PATH"
    mkdir -p "$RAW_DIR" "$NORMALIZED_DIR" "$TILES_DIR" "$CLASSIFIED_DIR"
    mkdir -p "$RASTERS_DIR" "$VECTORS_DIR" "$REPORTS_DIR" "$MANIFESTS_DIR"
    mkdir -p "$GROUND_TAO_RESULTS_DIR" "$GROUND_TAO_DEFAULT_SPECS_DIR" "$MODEL_REGISTRY_ROOT"
}

p2_print_config() {
    cat <<EOF
================ CONFIGURACAO P2 ================
PIPELINE_NAME                 : $PIPELINE_NAME
P2_PIPELINE_KIND              : $P2_PIPELINE_KIND
P2_PIPELINE_VERSION           : $P2_PIPELINE_VERSION
P2_TRAIN_VERSION              : $P2_TRAIN_VERSION
P2_INFER_VERSION              : $P2_INFER_VERSION
P2_MODEL_VERSION              : $P2_MODEL_VERSION
DATASET                       : $DATASET
DATASET_SLUG                  : $DATASET_SLUG
GPU                           : $GPU
GPU_PROFILE                   : $GPU_PROFILE
P2_EXECUTION_MODE             : $P2_EXECUTION_MODE
PROJECT_ROOT                  : $PROJECT_ROOT
HOST_ROOT                     : $HOST_ROOT
P2_CODE_ROOT                : $P2_CODE_ROOT
P2_CODE_DIR                 : $P2_CODE_DIR
ORIGINAL_IMAGES_DIR           : $ORIGINAL_IMAGES_DIR
DATA_HOST                     : $DATA_HOST
DATA_HOST_BASE                : $DATA_HOST_BASE
TAO_DATA_HOST                 : $TAO_DATA_HOST
SCRIPTS_HOST                  : $SCRIPTS_HOST
RESULTS_HOST                  : $RESULTS_HOST
MODEL_REGISTRY_ROOT           : $MODEL_REGISTRY_ROOT
WORKSPACE                     : $WORKSPACE
OUTPUT_PATH                   : $OUTPUT_PATH
TAO_DOCKER_COMPOSE_FILE       : $TAO_DOCKER_COMPOSE_FILE
TAO_IMAGE                     : $TAO_IMAGE
P2_ENV                        : $P2_ENV
TAO_CONTAINER_DATA_ROOT       : $TAO_CONTAINER_DATA_ROOT
TAO_CONTAINER_SCRIPTS_ROOT    : $TAO_CONTAINER_SCRIPTS_ROOT
TAO_CONTAINER_RESULTS_ROOT    : $TAO_CONTAINER_RESULTS_ROOT
GROUND_TAO_SUBCOMMAND         : $GROUND_TAO_SUBCOMMAND
GROUND_TAO_SPEC_FILE          : $GROUND_TAO_SPEC_FILE
GROUND_TAO_RESULTS_DIR        : $GROUND_TAO_RESULTS_DIR
GROUND_DATASET_ROOT           : $GROUND_DATASET_ROOT
GROUND_GENERATED_SPEC_FILE    : $GROUND_GENERATED_SPEC_FILE
PREPROCESS_MIN_TILE_AREA_PERCENT: $PREPROCESS_MIN_TILE_AREA_PERCENT
PREPROCESS_LABEL_SOURCE       : $PREPROCESS_LABEL_SOURCE
PREPROCESS_ASPRS_GROUND_CLASSES: $PREPROCESS_ASPRS_GROUND_CLASSES
PREPROCESS_ASPRS_VEGETATION_CLASSES: $PREPROCESS_ASPRS_VEGETATION_CLASSES
PREPROCESS_ASPRS_BUILDING_CLASSES: $PREPROCESS_ASPRS_BUILDING_CLASSES
PREPROCESS_ASPRS_PAVED_SURFACE_CLASSES: $PREPROCESS_ASPRS_PAVED_SURFACE_CLASSES
PREPROCESS_ASPRS_WATER_CLASSES: $PREPROCESS_ASPRS_WATER_CLASSES
PREPROCESS_MIN_LABELED_POINT_PERCENT: $PREPROCESS_MIN_LABELED_POINT_PERCENT
P2_INPUT_POINT_CLOUD          : $P2_INPUT_POINT_CLOUD
NORMALIZED_POINT_CLOUD        : $NORMALIZED_POINT_CLOUD
CLASSIFIED_POINT_CLOUD        : $CLASSIFIED_POINT_CLOUD
DTM_RAW_TIF                   : $DTM_RAW_TIF
DTM_REFINED_TIF               : $DTM_REFINED_TIF
CONTOUR_OUTPUT                : $CONTOUR_OUTPUT
PIPELINE_LOG                  : $PIPELINE_LOG
METRICS_CSV                   : $METRICS_CSV
=================================================
EOF
}
